// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0awYLXROJM_gcq_60dLUMnenIRU4cNJE',
    appId: '1:305515487204:web:09e824745dbf5111f731f1',
    messagingSenderId: '305515487204',
    projectId: 'deployment-b13d9',
    authDomain: 'deployment-b13d9.firebaseapp.com',
    storageBucket: 'deployment-b13d9.firebasestorage.app',
    measurementId: 'G-E2CR5ENEP5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpcvzOxHUS5ZKZnL7UgmLQJXeeqELu5sU',
    appId: '1:305515487204:android:f7b6b5f361f3d7d8f731f1',
    messagingSenderId: '305515487204',
    projectId: 'deployment-b13d9',
    storageBucket: 'deployment-b13d9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAx7RR6GiIex3zi7MKEVpzbXR1XcDuZXG0',
    appId: '1:305515487204:ios:fa0ee8dfd2abb28df731f1',
    messagingSenderId: '305515487204',
    projectId: 'deployment-b13d9',
    storageBucket: 'deployment-b13d9.firebasestorage.app',
    iosBundleId: 'com.example.deploymentLearning',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAx7RR6GiIex3zi7MKEVpzbXR1XcDuZXG0',
    appId: '1:305515487204:ios:fa0ee8dfd2abb28df731f1',
    messagingSenderId: '305515487204',
    projectId: 'deployment-b13d9',
    storageBucket: 'deployment-b13d9.firebasestorage.app',
    iosBundleId: 'com.example.deploymentLearning',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0awYLXROJM_gcq_60dLUMnenIRU4cNJE',
    appId: '1:305515487204:web:dd0c3f8858990a12f731f1',
    messagingSenderId: '305515487204',
    projectId: 'deployment-b13d9',
    authDomain: 'deployment-b13d9.firebaseapp.com',
    storageBucket: 'deployment-b13d9.firebasestorage.app',
    measurementId: 'G-6E019H3G8V',
  );
}
